export enum todoTypes {
  ADD_TODO = "ADD_TODO",
  FETCH_TODO = "FETCH_TODO",
  REMOVE_TODO = "REMOVE_TODO",
  UPDATE_TODO = "UPDATE_TODO",
  COMPLETE_TODO = "COMPLETE_TODO",
  FETCH_TODO_SUCS = "FETCH_TODO_SUCS",
  FETCH_TODO_ERROR = "FETCH_TODO_ERROR",
  CLEARE_COMPLETE_TODO = "CLEAR_COMPLETE_TODO",
}
